version: '3.7'

services:
  api:
    container_name: ${PROJECT:-microservices-in-action}-api
    image: microservices-in-action/api:prod
    build:
      context: ./services/api
      dockerfile: ./deployments/api.prod.dockerfile
    ports:
      - '3000:3000'
    restart: on-failure
